### ISSUE TITLE
problem with install layers (again)

### ISSUE THREAD

**Issue by ysolis** [newrelic/newrelic-lambda-cli#174]
## Description

i reported a previous issue (https://github.com/newrelic/newrelic-lambda-cli/issues/172) the bug was corrected but appears other related.

## Steps to Reproduce

i am installing/updating my layers in AWS CodeBuild

**buildspec.yml**

```
####################################
#
# Require: ubuntu ec2 instance
#
####################################
version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
    - apt update -y
    - apt install nodejs -y
    - npm install -g serverless
    - npm install
    - pip3 install newrelic-lambda-cli
  build:
    commands:
    - sls deploy --stage $stage --region $region -v
  post_build:
    commands:
      - newrelic-lambda layers install --function all --nr-account-id XXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXX --upgrade --aws-region $region

```
this is failing in the **post_build** process

## Expected Behaviour

finalized build without problems

## Relevant Logs / Console output

AWS Code Build **post_build** log:

```
[Container] 2021/05/17 01:28:54 Running command newrelic-lambda layers install --nr-account-id XXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXX --upgrade --aws-region $region
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.8/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in install
    install_success = all(future.result() for future in as_completed(futures))
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in <genexpr>
    install_success = all(future.result() for future in as_completed(futures))
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/newrelic_lambda_cli/utils.py", line 57, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 191, in install
    nr_account_id, policy_arn = _get_license_key_outputs(input.session)
  File "/root/.pyenv/versions/3.8.8/lib/python3.8/site-packages/newrelic_lambda_cli/integrations.py", line 713, in _get_license_key_outputs
    account_id, policy_arn = _get_stack_output_value(
TypeError: cannot unpack non-iterable NoneType object

[Container] 2021/05/17 01:28:57 Command did not exit successfully newrelic-lambda layers install --function all --nr-account-id XXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXX --upgrade --aws-region $region exit status 1
[Container] 2021/05/17 01:28:57 Phase complete: POST_BUILD State: FAILED
[Container] 2021/05/17 01:28:57 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: newrelic-lambda layers install --function all --nr-account-id XXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXX --upgrade --aws-region $region. Reason: exit status 1

```

## Your Environment

the problem is happening in AWS Code Build process, this is using Python 3.8 integrated in AWS Image in the build process

**Comment by kolanos** [comment]
@ysolis Thanks for reporting (again). This bug should be fixed in `v0.6.2`. Please let us know if you have any other issues.
