### ISSUE TITLE
integrations install command not working

### ISSUE THREAD

**Issue by alangford** [newrelic/newrelic-lambda-cli#176]
When attempting to install the new-relic lambda in my aws account it errors out

## Description

I am unable to install the lambda intergrations lambda. when running the steps according to the docs I receive the following error.

Traceback (most recent call last):
  File "/usr/local/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in install
    install_success = all(future.result() for future in as_completed(futures))
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in <genexpr>
    install_success = all(future.result() for future in as_completed(futures))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/utils.py", line 57, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/layers.py", line 192, in install
    nr_account_id, policy_arn = _get_license_key_outputs(input.session)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/integrations.py", line 717, in _get_license_key_outputs
    output_values = _get_stack_output_value(session, ["NrAccountId", "ViewPolicyARN"])
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/integrations.py", line 726, in _get_stack_output_value
    stacks = client.describe_stacks(StackName=LICENSE_KEY_STACK_NAME).get(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 608, in _make_api_call
    http, parsed_response = self._endpoint.make_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 169, in _send_request
    success_response, exception = self._get_response(
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 247, in _get_response
    parsed_response = parser.parse(
  File "/usr/local/lib/python3.9/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/usr/local/lib/python3.9/site-packages/botocore/parsers.py", line 440, in _do_error_parse
    self._replace_nodes(parsed)
  File "/usr/local/lib/python3.9/site-packages/botocore/parsers.py", line 395, in _replace_nodes
    if value.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

## Steps to Reproduce

 pip3 install --upgrade newrelic-lambda-cli
newrelic-lambda integrations install --nr-account-id xxxxx \
--nr-api-key xxxx-xxxxxxxx

## Expected Behaviour

It should install the newrelic-lambda integration lambda

## Relevant Logs / Console output
Traceback (most recent call last):
  File "/usr/local/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in install
    install_success = all(future.result() for future in as_completed(futures))
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in <genexpr>
    install_success = all(future.result() for future in as_completed(futures))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/utils.py", line 57, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/layers.py", line 192, in install
    nr_account_id, policy_arn = _get_license_key_outputs(input.session)
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/integrations.py", line 717, in _get_license_key_outputs
    output_values = _get_stack_output_value(session, ["NrAccountId", "ViewPolicyARN"])
  File "/usr/local/lib/python3.9/site-packages/newrelic_lambda_cli/integrations.py", line 726, in _get_stack_output_value
    stacks = client.describe_stacks(StackName=LICENSE_KEY_STACK_NAME).get(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 608, in _make_api_call
    http, parsed_response = self._endpoint.make_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 169, in _send_request
    success_response, exception = self._get_response(
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 247, in _get_response
    parsed_response = parser.parse(
  File "/usr/local/lib/python3.9/site-packages/botocore/parsers.py", line 210, in parse
    parsed = self._do_error_parse(response, shape)
  File "/usr/local/lib/python3.9/site-packages/botocore/parsers.py", line 440, in _do_error_parse
    self._replace_nodes(parsed)
  File "/usr/local/lib/python3.9/site-packages/botocore/parsers.py", line 395, in _replace_nodes
    if value.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

## Your Environment

MacOS 11.4
Python3 3.9.5
awscli 2.2.9

**Comment by alangford** [comment]
the layers install command is also not working and gives the same output

newrelic-lambda layers install \
 -f all  \
 --nr-account-id xxxxx -p profile

**Comment by kolanos** [comment]
@alangford Thanks for reporting this issue. What version of `botocore` do you have installed? This appears to be a bug there and not the CLI itself. We don't currently pin to a botocore version, but perhaps we should.

**Comment by alangford** [comment]
1.8.50

**Comment by alangford** [comment]
Thank you that fixed it! I just updated botocore to the latest and it is now working.

**Comment by kolanos** [comment]
Am able to reproduce with botocore 1.8.50. Glad you got it working.
