### ISSUE TITLE
error when try to install layer from shell

### ISSUE THREAD

**Issue by ysolis** [newrelic/newrelic-lambda-cli#184]
## Description

I try to install the layer in function set, but fails with a weird error, Tested with venvs with Python 3.8 and 3.9

## Steps to Reproduce

execute
```
❯ newrelic-lambda layers install --function all --nr-account-id XXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXXXXXXXX  --upgrade
```

## Expected Behaviour
layer correctly installed

## Relevant Logs / Console output
```
❯ newrelic-lambda layers install --function all --nr-account-id XXXXXXXX --nr-api-key NRAK-XXXXXXXXXXXXXXXXXXXXXXXXXXX --upgrade
Traceback (most recent call last):
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in install
    install_success = all(future.result() for future in as_completed(futures))
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in <genexpr>
    install_success = all(future.result() for future in as_completed(futures))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/utils.py", line 61, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 244, in install
    update_kwargs = _add_new_relic(input, config, nr_license_key)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 122, in _add_new_relic
    new_relic_layer = layer_selection(available_layers, runtime, architecture)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 51, in layer_selection
    response = enquiries.choose(
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/enquiries/choices.py", line 16, in choose
    options = choice_list.run(window)
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/enquiries/choices.py", line 54, in run
    with Input() as keyGen:
  File "/home/yonsy/devops/bairesdev/dummyclient/old_repos/.direnv/python-3.8.12/lib/python3.8/site-packages/curtsies/input.py", line 118, in __enter__
    signal.set_wakeup_fd(wfd, warn_on_full_buffer=False)
ValueError: set_wakeup_fd only works in main thread

```

## Your Environment
ArchLinux
Python 3.8 from a vritualenv

**Comment by kolanos** [comment]
This should be fixed in #186, which was included in `v0.6.6`.
