### ISSUE TITLE
ValueError: set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by bohn002** [newrelic/newrelic-lambda-cli#187]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

`newrelic-lambda layers install -f [FUNCTION_NAME] --nr-account-id [NR_ACCT_ID]`
results in a error: `ValueError: set_wakeup_fd only works in main thread` . Have tried older newrelic-lambda packages and switching python 3.9 with 3.8 but with the same error. If i switch the `-f` flag to `all` it will process the existing lambdas but then crash out with the same error message. Looks like there was a fix put in with #186 but not sure it worked.

## Steps to Reproduce
`newrelic-lambda layers install -f [FUNCTION_NAME] --nr-account-id [NR_ACCT_ID]`
or 
`newrelic-lambda layers install -f all --nr-account-id [NR_ACCT_ID]`

## Expected Behaviour

deploy lambda instrumentation

## Relevant Logs / Console output

```
Traceback (most recent call last):
  File "/Users/bonk/.pyenv/versions/test-nr/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in install
    install_success = all(future.result() for future in as_completed(futures))
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in <genexpr>
    install_success = all(future.result() for future in as_completed(futures))
  File "/Users/bonk/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/bonk/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/bonk/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/utils.py", line 61, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 255, in install
    update_kwargs = _add_new_relic(input, config, nr_license_key)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 133, in _add_new_relic
    new_relic_layer = layer_selection(available_layers, runtime, architecture)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/newrelic_lambda_cli/layers.py", line 55, in layer_selection
    response = enquiries.choose(
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/enquiries/choices.py", line 16, in choose
    options = choice_list.run(window)
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/enquiries/choices.py", line 54, in run
    with Input() as keyGen:
  File "/Users/bonk/.pyenv/versions/3.8.11/envs/test-nr/lib/python3.8/site-packages/curtsies/input.py", line 118, in __enter__
    signal.set_wakeup_fd(wfd, warn_on_full_buffer=False)
ValueError: set_wakeup_fd only works in main thread
```

## Your Environment

Intel Mac 11.6.1
Iterm2
PyEnv - Python 3.8.11 & 3.9.9
```
❯ pip list
Package             Version
------------------- ---------
blessings           1.7
boto3               1.20.16
botocore            1.23.16
certifi             2021.10.8
charset-normalizer  2.0.8
click               8.0.3
colorama            0.4.4
curtsies            0.3.10
cwcwidth            0.1.5
emoji               1.6.1
enquiries           0.1.0
gql                 2.0.0
graphql-core        2.3.2
idna                3.3
jmespath            0.10.0
newrelic-lambda-cli 0.6.6
pip                 21.3.1
promise             2.3
python-dateutil     2.8.2
requests            2.26.0
Rx                  1.6.1
s3transfer          0.5.0
setuptools          56.0.0
six                 1.16.0
tabulate            0.8.9
urllib3             1.26.7
```

## Additional context
Seems the same as #184

**Comment by kolanos** [comment]
@bohn002 Thanks for reporting. What Lambda runtime does this error on? A workaround would be to use `--layer-arn` to explicitly specify a layer ARN to use.

**Comment by bohn002** [comment]
@kolanos the specific Lambda is a Python 3.9, when doing the `all` option its a mix of Python 2.7, 3.6, 3.7, 3.8, 3.9 and Node 12. Looks like the "all" option also only parses 21 of the 38 existing lambdas not including the one I was specifically targeting. 

Tried the workaround:
`newrelic-lambda layers install  -f <SingleLambda> --layer-arn arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicPython39:1 --nr-account-id <NR_Account_ID> -u` and was able to have it install the layer on the targeted lambda and during an "all" run was able to have it show up as a parsed lambda now, but with the same ending error about `set_wakeup_fd`

**Comment by bohn002** [comment]
Works great. Thanks @kolanos
