### ISSUE TITLE
KeyError: 'Runtime'

### ISSUE THREAD

**Issue by cabal-daniel** [newrelic/newrelic-lambda-cli#216]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

```
Traceback (most recent call last):
  File "/Users/danhu/fileread/cabal/bin/newrelic-lambda", line 8, in <module>
    sys.exit(main())
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/newrelic_lambda_cli/cli/__init__.py", line 25, in main
    cli()
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in install
    install_success = all(future.result() for future in as_completed(futures))
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/newrelic_lambda_cli/cli/layers.py", line 126, in <genexpr>
    install_success = all(future.result() for future in as_completed(futures))
  File "/usr/local/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/newrelic_lambda_cli/utils.py", line 61, in _boto_error_wrapper
    return func(*args, **kwargs)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/newrelic_lambda_cli/layers.py", line 261, in install
    update_kwargs = _add_new_relic(input, config, nr_license_key)
  File "/Users/danhu/fileread/cabal/lib/python3.9/site-packages/newrelic_lambda_cli/layers.py", line 86, in _add_new_relic
    runtime = config["Configuration"]["Runtime"]
```

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

```
newrelic-lambda layers install --nr-account-id XXXXX --function all --upgrade
```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

- python3.9
- AWS
- lambdas deployed with serverless framework
- Lambdas are containerized
- Runtime is supposed to python3.9

```
frameworkVersion: '3'

provider:
  name: aws
  region: us-west-2
  runtime: python3.9
  architecture: arm64
  memorySize: 128
```

Not sure if runtime is always supposed to be returned. Perhaps serverless ignores it if we are using a containerized environment?

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by hmstepanek** [comment]
We don't support containerized lambdas. We do already have a feature request open to support it in our backlog.

**Comment by chaudharysaket** [comment]
We have released support for containerized Lambda. Please find the [New Relic instrumentation docs](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/instrument-lambda-function/containerized-images/). Thank you!
